#!/bin/sh

# Change to the directory containing the scripts
cd git-scripts

# Create an array from the output of the ls command, excluding README.md and the install script
files=($(ls | grep -v -e 'README.md' -e 'install'))

# Remove old scripts from ~/.local/bin
for file in "${files[@]}"; do
    rm -f ~/.local/bin/"$file"
done

echo "Old scripts have been removed, new scripts will be added"

# Copy new scripts to ~/.local/bin
cp "${files[@]}" ~/.local/bin

echo "New scripts have been added to ~/.local/bin"
